# Generated by Django 5.0.6 on 2024-05-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_alter_healthfacilities_healthcare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacilities',
            name='amenity',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='healthfacilities',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='healthfacilities',
            name='operator',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
